# Generated by Django 4.0.6 on 2022-07-25 04:23

import django.core.files.storage
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('profile_img', models.ImageField(blank=True, default='images/init/ryan.jpg', storage=django.core.files.storage.FileSystemStorage(), upload_to=profiles.models.upload_to)),
                ('introduce', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
